### ISSUE TITLE
food poisoning delay

### ISSUE THREAD

**Issue by fortrus2** [zeobviouslyfakeacc/HungerRevamped#1]
Hey, loving the mod, cant play without it! I just had food poisoning hit me in the middle of sleeping and it nailed my condition. I'm thinking it might be a good idea to wake the player when it hits. Thank you for all your mods - they've made my play experience so much better.

**Comment by zeobviouslyfakeacc** [comment]
Yeah, that's an issue, but I'm not sure if waking the player up is really the right course of action. No other affliction wakes you up (except for maybe cabin fever?). Maybe I'll just reduce the condition damage while sleeping or something like that 😄

**Comment by fortrus2** [comment]
i think ive gotten used to the food poisoning, just being very careful, eating only good stuff in the range of where it can effect me while sleeping. it just seemed very bad when it came out of nowhere! plus it seems food poisoning is extremely rare, so its not so bad unless you try to sleep while low condition and after eating a bad can of dog food.

on another note, relentless night does wake you up when freezing. (so you dont die without knowing why? im not sure.)

**Comment by zeobviouslyfakeacc** [comment]
I reduced the food poisoning damage while sleeping by 75% in [v1.4.1](https://github.com/zeobviouslyfakeacc/HungerRevamped/releases/tag/v1.4.1). In the worst-case scenario (if you get food poisoning just after going to sleep for 12 hours), you'll now only get 30% damage. So it's still somewhat punishing, but it won't get you down to 15% condition immediately 😃 

Thanks for reporting this issue!
