### ISSUE TITLE
Hi, this is more a question not for this mod, but for mods in general.

### ISSUE THREAD

**Issue by d1ret** [zeobviouslyfakeacc/HungerRevamped#3]
Do you think it is possible to create a multiplayer mod based on MelonLoader?

**Comment by zeobviouslyfakeacc** [comment]
No. TLD was never made for multiplayer. Even if you were able to figure out a clever game design that works in multiplayer and doesn't turn the entire game on its head, you'd still need way too much developer time to make anything like that.

Also, why ask something like that in a GitHub issue of HungerRevamped? The TLD reddit exists, so does the TLD modding discord server.
